### ISSUE TITLE
Problems installing bower

### ISSUE THREAD

**Issue by fritzrichter** [srs/gradle-gulp-plugin#12]
Hi there,
I configured my java project and added these two lines to my Gradle config. 

```
classpath("com.moowork.gradle:gradle-gulp-plugin:0.10")
classpath("com.moowork.gradle:gradle-node-plugin:0.10")
```

If I run `./gradlew gulp_build`, I get the following exception. Locally when I do a `bower install` it works fine. Any idea how to solve that?

```
ads@build01:~/agent/build01/work/fa7926048c830c7d$ ./gradlew  gulp build
:nodeSetup UP-TO-DATE
:installGulp UP-TO-DATE
:npmSetup SKIPPED
:npmInstall UP-TO-DATE
:gulp_build
[10:02:52] Using gulpfile ~/agent/build01/work/fa7926048c830c7d/src/main/web/gulpfile.js
[10:02:52] Starting 'styles'...
[10:02:53] Starting 'partials'...
[10:02:53] Starting 'images'...
[10:02:53] Starting 'fonts'...
[10:02:53] 'fonts' errored after 24 ms
[10:02:53] Error: Bower components directory does not exist at /home/ads/agent/build01/work/fa7926048c830c7d/src/main/web/bower_components
    at Object.module.exports (/home/ads/agent/build01/work/fa7926048c830c7d/src/main/web/node_modules/main-bower-files/lib/index.js:48:15)
    at Gulp.<anonymous> (/home/ads/agent/build01/work/fa7926048c830c7d/src/main/web/gulp/build.js:72:21)
    at module.exports (/home/ads/agent/build01/work/fa7926048c830c7d/src/main/web/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/ads/agent/build01/work/fa7926048c830c7d/src/main/web/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/ads/agent/build01/work/fa7926048c830c7d/src/main/web/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/ads/agent/build01/work/fa7926048c830c7d/src/main/web/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /home/ads/agent/build01/work/fa7926048c830c7d/src/main/web/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error
    at new Parser (/home/ads/agent/build01/work/fa7926048c830c7d/src/main/web/node_modules/gulp-less/node_modules/less/lib/less/parser.js:333:27)
    at Object.less.render (/home/ads/agent/build01/work/fa7926048c830c7d/src/main/web/node_modules/gulp-less/node_modules/less/lib/less/index.js:18:22)
    at Transform._transform (/home/ads/agent/build01/work/fa7926048c830c7d/src/main/web/node_modules/gulp-less/index.js:38:10)
    at Transform._read (/home/ads/agent/build01/work/fa7926048c830c7d/src/main/web/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/home/ads/agent/build01/work/fa7926048c830c7d/src/main/web/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/home/ads/agent/build01/work/fa7926048c830c7d/src/main/web/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/home/ads/agent/build01/work/fa7926048c830c7d/src/main/web/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/home/ads/agent/build01/work/fa7926048c830c7d/src/main/web/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/home/ads/agent/build01/work/fa7926048c830c7d/src/main/web/node_modules/gulp-filter/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/home/ads/agent/build01/work/fa7926048c830c7d/src/main/web/node_modules/gulp-filter/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
:gulp_build FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gulp_build'.
> Process 'command '/home/ads/agent/build01/work/fa7926048c830c7d/build/nodejs/node-v0.12.5-linux-x64/bin/node'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by fritzrichter** [comment]
I added the bower install as task to gulp, no it's working
